// generate-css.mjs — dual-flavor CSS emitter from the tiered token spec.
//
// Flavor 1 (library):  packages/react/src/styles/tokens.css
//   Unprefixed shadcn-standard semantic tokens (CORE LAYER ONLY), launcher
//   preset values: :root (light) + .dark + [data-theme] accent overrides.
//   Hosts that define these variables (launcher, any shadcn app) win —
//   cha-set components follow host theming automatically.
// Flavor 2 (compat):   dist/consumers/launcher/generated/tokens.generated.css
//   Unprefixed custom properties reproducing the launcher's hand-written
//   variable layers IN SOURCE CASCADE ORDER:
//     semantic defaults (:root/.dark)          <- replaces shadcn-base.css vars
//     composite surfaces (:root/.dark)         <- replaces app-variables.css
//     window-tint override blocks              <- replaces window-tint.css
//     interface-style override blocks          <- replaces themes.css head
//     accent-theme override blocks             <- replaces themes.css body
// Fails loud (exit 1) on any spec/validation error before writing anything.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateSpec } from '../validate-tokens.mjs';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const spec = JSON.parse(readFileSync(resolve(repoRoot, 'spec', 'tokens.json'), 'utf8'));

const errors = validateSpec(spec);
if (errors.length) {
  console.error(`[gen:css] tokens.json invalid (${errors.length}):`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

// Dunting-only semantic tokens use dotted namespaces (chrome.icon). The
// launcher preset's original custom property drops the namespace prefix
// (interaction.hover -> --hover); flat keys are identity.
const cssName = (key) => key.split('.').pop();

const decl = (prop, value) => `  ${prop}: ${value};`;

function semanticBlocks(prefix, coreOnly = false) {
  const light = [];
  const dark = [];
  for (const [key, def] of Object.entries(spec.semantic)) {
    const presets = def.presets ?? {};
    const l = presets.launcher?.light;
    const d = presets.launcher?.dark;
    if (l === undefined && d === undefined) continue; // dunting-only token
    const name = cssName(key);
    if (coreOnly && !LIB_CORE_TOKENS.has(name)) continue;
    const prop = `${prefix}${name}`;
    if (l !== undefined) light.push(decl(prop, l));
    if (d !== undefined) dark.push(decl(prop, d));
  }
  return { light, dark };
}

function selectorBlock(selector, decls) {
  return `${selector} {\n${decls.join('\n')}\n}`;
}

// Core layer = the shadcn-standard semantic vocabulary, emitted UNPREFIXED.
// Binding to these exact names is the contract: any host that defines them
// (launcher, any shadcn/Tailwind app) themes cha-set components for free.
// Tokens outside this set (hover, sidebar-selected, fontWeight, …) stay out
// of the library flavor until an extension-layer policy exists; they remain
// reachable through the compat flavor / spec primitives.
const LIB_CORE_TOKENS = new Set([
  'background', 'foreground',
  'card', 'card-foreground', 'popover', 'popover-foreground',
  'primary', 'primary-foreground', 'secondary', 'secondary-foreground',
  'muted', 'muted-foreground', 'accent', 'accent-foreground',
  'destructive', 'destructive-foreground', 'border', 'input', 'ring',
  'sidebar', 'sidebar-foreground', 'sidebar-primary', 'sidebar-primary-foreground',
  'sidebar-accent', 'sidebar-accent-foreground', 'sidebar-border', 'sidebar-ring',
  'chart-1', 'chart-2', 'chart-3', 'chart-4', 'chart-5',
  'radius',
]);

// ---------------- Flavor 1: library (shadcn-standard core) ----------------
{
  const { light, dark } = semanticBlocks('--', true);

  // Accent themes: [data-theme] overrides let consumers switch accent hue at
  // runtime (document.documentElement.dataset.theme = 'violet'). Values are
  // the launcher preset's accent overrides, verbatim.
  const accentBlocks = [];
  for (const o of spec.themes.overrides) {
    if (!('accentTheme' in o)) continue;
    const decls = Object.entries(o.tokens).map(([n, v]) => decl(`--${cssName(n)}`, v));
    accentBlocks.push(selectorBlock(o.selector, decls));
  }

  const out = [
    '/* GENERATED by spec/generators/generate-css.mjs — DO NOT EDIT.',
    ' * Source: spec/tokens.json (preset: launcher). Unprefixed shadcn-standard',
    ' * core tokens — hosts that define them take precedence.',
    ' * Regenerate: pnpm gen:css */',
    selectorBlock(':root', light),
    '',
    selectorBlock('.dark', dark),
    '',
    '/* == accent themes (switch via [data-theme] on <html>) == */',
    accentBlocks.join('\n'),
    '',
  ].join('\n');

  const outFile = resolve(repoRoot, 'packages', 'react', 'src', 'styles', 'tokens.css');
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, out, 'utf8');
  console.log(`[gen:css] library flavor -> ${outFile}`);
}

// ---------------- Flavor 2: launcher compat (unprefixed) ----------------
{
  const overrides = spec.themes.overrides;
  const byAxis = (axis) => overrides.filter((o) => axis in o);

  const parts = [];
  parts.push('/* GENERATED by spec/generators/generate-css.mjs — DO NOT EDIT.');
  parts.push(' * Source: spec/tokens.json (preset: launcher). Cascade order mirrors the');
  parts.push(' * hand-written files this file replaces: shadcn-base -> app-variables ->');
  parts.push(' * window-tint -> interface-style -> accent-themes. Regenerate: pnpm gen:css */');

  // Layer 1+2: semantic defaults, then composites (:root light / .dark dark)
  const sem = semanticBlocks('--');
  parts.push('');
  parts.push('/* == semantic defaults (was shadcn-base.css var blocks) == */');
  parts.push(selectorBlock(':root', sem.light));
  parts.push('');
  parts.push(selectorBlock('.dark', sem.dark));

  const compLight = [];
  const compDark = [];
  for (const [key, def] of Object.entries(spec.composite.launcher)) {
    if (!def.$platform.includes('css')) continue;
    if (def.light !== undefined) compLight.push(decl(`--${key}`, def.light));
    if (def.dark !== undefined) compDark.push(decl(`--${key}`, def.dark));
  }
  parts.push('');
  parts.push('/* == composite surfaces (was app-variables.css) == */');
  parts.push(selectorBlock(':root', compLight));
  parts.push('');
  parts.push(selectorBlock('.dark', compDark));

  // Layer 3: window tints (source order: 6 light then 6 dark)
  parts.push('');
  parts.push('/* == window tint overrides (was window-tint.css) == */');
  for (const o of byAxis('windowTint')) {
    parts.push('');
    parts.push(selectorBlock(o.selector, Object.entries(o.tokens).map(([n, v]) => decl(`--${n}`, v))));
  }

  // Layer 4: interface style (themes.css head — BEFORE accent themes, matching source)
  parts.push('');
  parts.push('/* == interface-style overrides (was themes.css head) == */');
  for (const o of byAxis('interfaceStyle')) {
    parts.push('');
    parts.push(selectorBlock(o.selector, Object.entries(o.tokens).map(([n, v]) => decl(`--${n}`, v))));
  }

  // Layer 5: accent themes (8 light :root[data-theme], then 8 dark)
  parts.push('');
  parts.push('/* == accent theme overrides (was themes.css body) == */');
  for (const o of byAxis('accentTheme')) {
    parts.push('');
    parts.push(selectorBlock(o.selector, Object.entries(o.tokens).map(([n, v]) => decl(`--${n}`, v))));
  }

  const out = parts.join('\n') + '\n';
  const outFile = resolve(repoRoot, 'dist', 'consumers', 'launcher', 'generated', 'tokens.generated.css');
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, out, 'utf8');
  console.log(`[gen:css] compat flavor   -> ${outFile}`);
}