// generate-css.mjs — dual-flavor CSS emitter from the tiered token spec.
//
// Flavor 1 (library):  packages/react/src/styles/tokens.css
//   --cs-* prefixed semantic tokens, launcher preset, :root (light) + .dark.
// Flavor 2 (compat):   dist/consumers/launcher/generated/tokens.generated.css
//   Unprefixed custom properties reproducing the launcher's hand-written
//   variable layers IN SOURCE CASCADE ORDER:
//     semantic defaults (:root/.dark)          <- replaces shadcn-base.css vars
//     composite surfaces (:root/.dark)         <- replaces app-variables.css
//     window-tint override blocks              <- replaces window-tint.css
//     interface-style override blocks          <- replaces themes.css head
//     accent-theme override blocks             <- replaces themes.css body
// Fails loud (exit 1) on any spec/validation error before writing anything.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateSpec } from '../validate-tokens.mjs';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const spec = JSON.parse(readFileSync(resolve(repoRoot, 'spec', 'tokens.json'), 'utf8'));

const errors = validateSpec(spec);
if (errors.length) {
  console.error(`[gen:css] tokens.json invalid (${errors.length}):`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

// Dunting-only semantic tokens use dotted namespaces (chrome.icon). The
// launcher preset's original custom property drops the namespace prefix
// (interaction.hover -> --hover); flat keys are identity.
const cssName = (key) => key.split('.').pop();

const decl = (prop, value) => `  ${prop}: ${value};`;

function semanticBlocks(prefix) {
  const light = [];
  const dark = [];
  for (const [key, def] of Object.entries(spec.semantic)) {
    const presets = def.presets ?? {};
    const l = presets.launcher?.light;
    const d = presets.launcher?.dark;
    if (l === undefined && d === undefined) continue; // dunting-only token
    const prop = `${prefix}${cssName(key)}`;
    if (l !== undefined) light.push(decl(prop, l));
    if (d !== undefined) dark.push(decl(prop, d));
  }
  return { light, dark };
}

function selectorBlock(selector, decls) {
  return `${selector} {\n${decls.join('\n')}\n}`;
}

// ---------------- Flavor 1: library (--cs-*) ----------------
{
  const { light, dark } = semanticBlocks('--cs-');
  const weight = spec.primitives.fontWeight ?? {};
  for (const [k, v] of Object.entries(weight)) light.push(decl(`--cs-font-weight-${k}`, String(v)));
  // keep .dark block aligned (weights are mode-invariant)
  for (const [k, v] of Object.entries(weight)) dark.push(decl(`--cs-font-weight-${k}`, String(v)));

  const out = [
    '/* GENERATED by spec/generators/generate-css.mjs — DO NOT EDIT.',
    ' * Source: spec/tokens.json (preset: launcher). Regenerate: pnpm gen:css */',
    selectorBlock(':root', light),
    '',
    selectorBlock('.dark', dark),
    '',
  ].join('\n');

  const outFile = resolve(repoRoot, 'packages', 'react', 'src', 'styles', 'tokens.css');
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, out, 'utf8');
  console.log(`[gen:css] library flavor -> ${outFile}`);
}

// ---------------- Flavor 2: launcher compat (unprefixed) ----------------
{
  const overrides = spec.themes.overrides;
  const byAxis = (axis) => overrides.filter((o) => axis in o);

  const parts = [];
  parts.push('/* GENERATED by spec/generators/generate-css.mjs — DO NOT EDIT.');
  parts.push(' * Source: spec/tokens.json (preset: launcher). Cascade order mirrors the');
  parts.push(' * hand-written files this file replaces: shadcn-base -> app-variables ->');
  parts.push(' * window-tint -> interface-style -> accent-themes. Regenerate: pnpm gen:css */');

  // Layer 1+2: semantic defaults, then composites (:root light / .dark dark)
  const sem = semanticBlocks('--');
  parts.push('');
  parts.push('/* == semantic defaults (was shadcn-base.css var blocks) == */');
  parts.push(selectorBlock(':root', sem.light));
  parts.push('');
  parts.push(selectorBlock('.dark', sem.dark));

  const compLight = [];
  const compDark = [];
  for (const [key, def] of Object.entries(spec.composite.launcher)) {
    if (!def.$platform.includes('css')) continue;
    if (def.light !== undefined) compLight.push(decl(`--${key}`, def.light));
    if (def.dark !== undefined) compDark.push(decl(`--${key}`, def.dark));
  }
  parts.push('');
  parts.push('/* == composite surfaces (was app-variables.css) == */');
  parts.push(selectorBlock(':root', compLight));
  parts.push('');
  parts.push(selectorBlock('.dark', compDark));

  // Layer 3: window tints (source order: 6 light then 6 dark)
  parts.push('');
  parts.push('/* == window tint overrides (was window-tint.css) == */');
  for (const o of byAxis('windowTint')) {
    parts.push('');
    parts.push(selectorBlock(o.selector, Object.entries(o.tokens).map(([n, v]) => decl(`--${n}`, v))));
  }

  // Layer 4: interface style (themes.css head — BEFORE accent themes, matching source)
  parts.push('');
  parts.push('/* == interface-style overrides (was themes.css head) == */');
  for (const o of byAxis('interfaceStyle')) {
    parts.push('');
    parts.push(selectorBlock(o.selector, Object.entries(o.tokens).map(([n, v]) => decl(`--${n}`, v))));
  }

  // Layer 5: accent themes (8 light :root[data-theme], then 8 dark)
  parts.push('');
  parts.push('/* == accent theme overrides (was themes.css body) == */');
  for (const o of byAxis('accentTheme')) {
    parts.push('');
    parts.push(selectorBlock(o.selector, Object.entries(o.tokens).map(([n, v]) => decl(`--${n}`, v))));
  }

  const out = parts.join('\n') + '\n';
  const outFile = resolve(repoRoot, 'dist', 'consumers', 'launcher', 'generated', 'tokens.generated.css');
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, out, 'utf8');
  console.log(`[gen:css] compat flavor   -> ${outFile}`);
}